Repository terraforming-mars/terraforming-mars, pull requests merged in 2021-01, with the labels that each got.

#2310 add basic support for watching changes
  package.json
  webpack.config.js
Labels: enhancement

#2481 Initial files for Polish translation
  src/constants.ts
  src/locales/pl/ares_cards.json
  src/locales/pl/base_corporations.json
  src/locales/pl/bigboxpromo.json
  src/locales/pl/cards.json
  src/locales/pl/colonies.json
  src/locales/pl/colonies_cards.json
  src/locales/pl/colonies_corporations.json
  src/locales/pl/community_corporations.json
  src/locales/pl/game_end.json
  src/locales/pl/help.iconography.json
  src/locales/pl/log_messages.json
  src/locales/pl/main_menu.json
  src/locales/pl/preferences.json
  src/locales/pl/prelude_cards.json
  src/locales/pl/prelude_corporations.json
  src/locales/pl/preludes.json
  src/locales/pl/ui.json
  src/locales/pl/venus_next.json
  src/locales/pl/venus_next_corporations.json
  src/styles/language_switcher.less
Labels: do not merge

#2563 Moon15: Steel Market Monopolists and Titanium Market Monopolists
  assets/moon/luna-mining-hub-special.png
  assets/moon/luna-mining-hub.png
  assets/moon/luna-trade-station-special.png
  assets/moon/luna-trade-station.png
  assets/moon/luna-train-station-special.png
  assets/moon/luna-train-station.png
  src/CardName.ts
  src/cards/base/RoboticWorkforce.ts
  src/cards/moon/AIControlledMineNetwork.ts
  src/cards/moon/AncientShipyards.ts
  src/cards/moon/ArchimedesHydroponicsStation.ts
  src/cards/moon/DeepLunarMining.ts
  src/cards/moon/IronExtractionCenter.ts
  src/cards/moon/LunaMiningHub.ts
  src/cards/moon/LunaResort.ts
  src/cards/moon/LunaStagingStation.ts
  src/cards/moon/LunaTradeStation.ts
  src/cards/moon/LunaTrainStation.ts
  src/cards/moon/LunarObservationPost.ts
  src/cards/moon/MarketCard.ts
  src/cards/moon/MiningRobotsManufCenter.ts
  src/cards/moon/MoonCard.ts
  src/cards/moon/MoonCardManifest.ts
  src/cards/moon/NewColonyPlanningInitiaitives.ts
  src/cards/moon/PrideoftheEarthArkship.ts
  src/cards/moon/SteelMarketMonopolists.ts
  src/cards/moon/TitaniumExtractionCenter.ts
  src/cards/moon/TitaniumMarketMonopolists.ts
  src/cards/render/CardRenderDynamicVictoryPoints.ts
  src/components/SelectSpace.ts
  src/components/card/CardRenderTileComponent.ts
  src/components/moon/MoonBoard.ts
  src/deferredActions/StealResources.ts
  src/moon/PlaceSpecialMoonTile.ts
  src/styles/moon.less
  tests/cards/CardMetadata.spec.ts
  tests/cards/moon/AIControlledMineNetwork.spec.ts
  tests/cards/moon/AncientShipyards.spec.ts
  tests/cards/moon/ArchimedesHydroponicsStation.spec.ts
  tests/cards/moon/DeepLunarMining.spec.ts
  tests/cards/moon/IronExtractionCenter.spec.ts
  tests/cards/moon/LunaMiningHub.spec.ts
  tests/cards/moon/LunaResort.spec.ts
  tests/cards/moon/LunaStagingStation.spec.ts
  tests/cards/moon/LunaTradeStation.spec.ts
  tests/cards/moon/LunaTrainStation.spec.ts
  tests/cards/moon/LunarObservationPost.spec.ts
  tests/cards/moon/MiningRobotsManufCenter.spec.ts
  tests/cards/moon/NewColonyPlanningInitiaitives.spec.ts
  tests/cards/moon/PrideoftheEarthArkship.spec.ts
  tests/cards/moon/SteelMarketMonopolists.spec.ts
  tests/cards/moon/TitaniumExtractionCenter.spec.ts
  tests/cards/moon/TitaniumMarketMonopolists.spec.ts
Labels: waiting-on-author
