Repository terraforming-mars/terraforming-mars, pull requests merged in 2021-03, with the labels that each got.

#2812 keep trying if error while waiting
  assets/index.html
  src/components/App.ts
  src/components/PlayerHome.ts
  src/components/WaitingFor.ts
Labels: enhancement

#2856 Added confirmation dialog when no inital cards selected
  src/components/SelectInitialCards.ts
  src/components/SelectSpace.ts
  src/components/common/ConfirmDialog.ts
Labels: enhancement

#2883 add turmoil policy use count, fix party boolean
  src/components/Party.ts
  src/components/Turmoil.ts
  src/models/TurmoilModel.ts
  src/styles/turmoil.less
Labels: enhancement

#2906 use pointer for log-card
  src/styles/log.less
Labels: enhancement

#2945 Add comment explaining why 5 is an acceptable number of MA randomization attempts.
  src/MilestoneAwardSelector.ts
Labels: non-critical

#2952 Add a (disabled) prototype for a sound when the log changes
  src/SoundManager.ts
  src/components/LogPanel.ts
  src/components/SoundManager.ts
  src/components/WaitingFor.ts
Labels: non-critical

#2953 use undoCount with gameAge for detecting changes
  src/Game.ts
  src/SerializedGame.ts
  src/components/WaitingFor.ts
  src/database/GameLoader.ts
  src/models/PlayerModel.ts
  src/routes/ApiWaitingFor.ts
  src/server/ServerModel.ts
  tests/database/Cloner.spec.ts
Labels: waiting-on-author

#2977 Add Desperate Measures test
  tests/cards/ares/DesperateMeasures.spec.ts
Labels: non-critical, variant

#3041 add ETag for waiting for route
  src/routes/ApiWaitingFor.ts
  tests/routes/ApiWaitingFor.spec.ts
  tests/routes/HttpMocks.ts
Labels: enhancement
